# Generated by Django 5.2.17 on 2026-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_rotatingworktype_name'),
        ('geofencing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofencing',
            name='exempt_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments exempt from the geofence check.', related_name='geofence_exemptions', to='base.department'),
        ),
    ]
